from pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel
ENV LANG=C.UTF-8
RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y tzdata \
    && ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && dpkg-reconfigure --frontend noninteractive tzdata
RUN rm /opt/conda/bin/ffmpeg
RUN apt-key adv --recv-keys --keyserver keyserver.ubuntu.com A4B469963BF863CC && apt-get -y install libx264-dev ffmpeg curl build-essential
COPY deploy /app/deploy
WORKDIR /app
RUN pip install --upgrade pip
RUN pip install -r deploy/requirements.txt